meta-openembedded: fribidi: Fix build with security flags turned on
Clang complains like below
| ../../fribidi-0.19.7/charset/fribidi-char-sets-cap-rtl.c:148:7: error: expected expression
|       DBG ("warning: could not find a mapping for CapRTL to Unicode:");

Therefore quick fix is to remove FORTIFY_SOURCE from cmdline

(From meta-openembedded rev: 1c8afeed179495a53e7b782b994e4a1f00f15536)

Signed-off-by: Khem Raj <raj.khem@gmail.com>